pub const ANCHOR_DISCRIMINATOR: usize = 8;
pub const MIN_AMOUNT_TO_RAISE: u64 = 3;
pub const SECONDS_TO_DAYS: i64 = 86400;
pub const DEFAULT_CONTRIBUTION_CAP_PERCENTAGE: u8 = 10;
pub const MIN_CONTRIBUTION_CAP_PERCENTAGE: u8 = 1;
pub const PERCENTAGE_SCALER: u64 = 100;
